### ISSUE TITLE
gitlab和jenkins的CI相关配置

### ISSUE THREAD

**Issue by lixingdecai** [lixingdecai/lixingdecai.github.io#5]
1. 配置.gitlab-ci.yml
```
stages:
  - build
variables:
  PROJECT_NAME: "rn-novels" // 工程名
  SECRET_KEY: "af496a85ad0a574bce21ce4f16b3f85b" // gitlab上生成的token, 用来配置在jenkins上
build:
  stage: build  // 触发jenkins
  script:
    - "curl http://192.168.10.142:8080/job/$PROJECT_NAME/build?token=$SECRET_KEY" // jenkins的地址、项目名、token
  only:
    - Tools  // 触发分支
```

2. 配置jenkins
